// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoatkyszoqkhtczrpsbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYXRreXN6b3FraHRjenJwc2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDE3OTMsImV4cCI6MjA3NDA3Nzc5M30.BsC0C7hM2e8WHt4A8a-XrFh1hLZyJ-dDSprZb2RQikI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});